# -*- coding: utf-8 -*-
"""Olá, este é o Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb

# Aula 4
"""

#o ponto em python é virgula, porém, para multiplicar é *#
#o type é para demonstrar qual a classe da variavel#
a = 3.3
b ="3.3"
print(type(a))
print(type(b))

numero1 = 5
numero2 = 3
resultado = numero1 + numero2

print(type(resultado))

esta_chovendo = False

if esta_chovendo:
  print("Está chovendo")
else:
  print("Não está chovendo")

#Para variaveis str é preciso das aspas no palavra, igual whey#
bebida = "Whey"
valor_bebida = 100.00
alcool = False
if alcool:
  print("Minha bebida favorita é",bebida,"custando R$",valor_bebida,"e contendo álcool")
else:
 print("Minha bebida favorita é",bebida,"custando R$",valor,"e não contendo álcool")

print(type(bebida))
print(type(valor_bebida))
print(type(alcool))

#o "f" junto com o {} em mensagem permite usar a variavel dentro de um texto#
bebida_favorita = "Café"
preco_bebida = 3.50
e_alcoolica = False

tipo_bebida = type(bebida_favorita).__name__
tipo_preco = type(preco_bebida).__name__
tipo_alcoolica = type(e_alcoolica).__name__

mensagem = f"Minha bebida favorita é: {bebida_favorita}, que custa {preco_bebida} e não é alcoólica"
mensagem_tipos = f"Os tipos das váriaveis são: bebida_favorita ({tipo_bebida}), preco_bebida ({tipo_preco}), e alcoolica ({tipo_alcoolica})."

print(mensagem)
print(mensagem_tipos)

"""#Operadores:
##Agora declaremos mais variáveis e usemos operados
"""

#atenção no type, no codigo acima, o __name__ não deixou aparecer class#
almoco = "Parmegiana"
valor_almoco = 30.50
carteira = 40.00

total = (carteira - valor_almoco - valor_bebida)

tipo_almoco = type(almoco)
tipo_valor = type(valor_almoco)
tipo_carteira = type(carteira)

mensagem = f"Comi uma {almoco} no meu almoço e gastei o valor de R$ {valor_almoco + valor_bebida}, e me restou R${total}!"
mensagem_tipos = f"Os tipos das váriaveis usadas foram: almoco {tipo_almoco}, valor_almoco {tipo_valor} e carteira {tipo_carteira}"

print(mensagem)
print(mensagem_tipos)

sobremesa = "Chocolate"
valor_sobremesa = 8.5
convidados = 5

total_sobremesa = valor_sobremesa * convidados
Conta_solo = valor_sobremesa + valor_bebida + valor_almoco
Conta_geral = (valor_almoco * convidados) + (valor_bebida * 3) + total_sobremesa
divisao = Conta_geral / convidados

print(Conta_solo)
print(Conta_geral)
print(divisao)

if carteira >= divisao:
  print("Vamos dividir a conta!")
else:
  print("Voces que lutem!")

bom_amigo = True

if carteira >= divisao:
  print("Vamos dividir a conta!")
elif bom_amigo == True:
  print("Se é você que vai pagar eu to dentro")
else:
  print("Voces que lutem!")