# -*- coding: utf-8 -*-
"""Olá, este é o Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb

# Aula 3

# Operadores Relativos
"""

soma = 4 - 9
print ("soma")

X = 2
Y = 1
X <= Y

"Lucas" == "lucas"

10 != 4

10 > 5 and 1 > 0

10 > 5 or 3 > 2

"""# Operadores Condicionais"""

#If é condicao, caso o resultado seja false não será executado#
if (100 < 5):
  print("Verdade, 100 é maior que 5")
print("Não faço parte do if")

#variavel nao precisa estar dentro do  parenteses, e o nome é case sensitive#
Nome = "Lucas"
if Nome == "Lucas":
  print("Entrei no bloco do if")
print ("Já não faço parte do if")

if 10 > 5 and 100 < 0:
  print("Não vou entrar aqui")
if 10 > 5 and 100 > 0:
  print("Entrei")

#a função else traz qualquer condição oposta ao if#
if "Bianca" == "Bianca":
  print("A condição é verdadeira")
else:
  print("A condição é falsa")
print("Eu rodo independente do if e do else")

"""#Input"""

#Input é a forma de mostrar na tela com a interação do usuario diferente de print#
idade = input("Informe a sua idade: ")
idade = int(idade)

if idade >= 18:
  print("Você está apto a tirar a carteira de motorista!")
else:
  print("Voce não está apto")

#elif busca outra condição#
if 8 < 3:
  print("Isso é falso")
elif 9 > 3:
  print("Verdade")
else:
  print("Talvez")

# elif é a função secundária caso o if seja false #
idade = input("Informe a sua idade: ")
idade = int(idade)

if idade < 18:
  print("Voce é jovem!")
  print("Espere mais um pouco")
elif idade < 35:
  print("Parabens")
  print("Boa lek")
else:
  print("Se fudeu")
print("Fim do programa")

"""# Operadores de Repetição"""

print("Um elefante incomoda muita gente...")
print("Um elefante incomoda muita gente...")
print("Um elefante incomoda muita gente...")
print("Um elefante incomoda muita gente...")
print("Um elefante incomoda muita gente...")
print("Um elefante incomoda muita gente...")
print("Um elefante incomoda muita gente...")
print("Um elefante incomoda muita gente...")
print("Um elefante incomoda muita gente...")

# white é enquanto para repetições #
Contador = 1

while Contador < 10:
  print("Um elefante incomoda muita gente...")

  Contador += 1
print("Aqui está fora do laço")

print("Contagem Regressiva")

contadorBomba = 3

while contadorBomba > 0:
  print(contadorBomba)

  contadorBomba -= 1
print("BOOM")

for i in range(0,31,2):
  print(i)